// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmPKKLw546AxxLYAhgOAYGPRN1cEDoDMc',
    appId: '1:496854739991:web:a48632e9c7ebc3139f8052',
    messagingSenderId: '496854739991',
    projectId: 'deu-cis',
    authDomain: 'deu-cis.firebaseapp.com',
    storageBucket: 'deu-cis.firebasestorage.app',
    measurementId: 'G-CH7G098FW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ly_GAyJ1VsoOuTqpBmxrnlPW3UDL28I',
    appId: '1:496854739991:android:7e159d1f55fd4b509f8052',
    messagingSenderId: '496854739991',
    projectId: 'deu-cis',
    storageBucket: 'deu-cis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfsF_agu2i7Avrst8DA6veAHiWrBstskM',
    appId: '1:496854739991:ios:dbe0f565495139469f8052',
    messagingSenderId: '496854739991',
    projectId: 'deu-cis',
    storageBucket: 'deu-cis.firebasestorage.app',
    iosBundleId: 'com.example.deuCis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfsF_agu2i7Avrst8DA6veAHiWrBstskM',
    appId: '1:496854739991:ios:dbe0f565495139469f8052',
    messagingSenderId: '496854739991',
    projectId: 'deu-cis',
    storageBucket: 'deu-cis.firebasestorage.app',
    iosBundleId: 'com.example.deuCis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmPKKLw546AxxLYAhgOAYGPRN1cEDoDMc',
    appId: '1:496854739991:web:88c51033583fa13b9f8052',
    messagingSenderId: '496854739991',
    projectId: 'deu-cis',
    authDomain: 'deu-cis.firebaseapp.com',
    storageBucket: 'deu-cis.firebasestorage.app',
    measurementId: 'G-DQWMXRPKDD',
  );
}
